### ISSUE TITLE
How can I find "8821cu.ko"?

### ISSUE THREAD

**Issue by gavinweixin** [Yuan-W/rtl8821cu#1]
Hi Yuan,

Thanks for your great work here. I just bought an adapter with RTL8821CU embedded and it seems there aren't many drivers for this chip on Linux yet.

Luckily, I find your project. But when I tried to run "sudo make install", it came out that "cannot stat '8821cu.ko': No such file or directory".

Actually, I know nothing about drivers. Could you please help me with this?

Thanks,
Gavin

**Comment by Yuan-W** [comment]
Hi Gavin,

It seems that the driver was not compiled successfully during the previous step. Is there any error message showing uop during the `sudo make` step?

**Comment by gavinweixin** [comment]
No, there isn't other error message. Here are all the messages.

> weixin@console:~/Driver/rtl8821cu$ sudo make install
> [sudo] password for weixin: 
> install -p -m 644 8821cu.ko  /lib/modules/4.4.0-112-generic/kernel/drivers/net/wireless/
> install: cannot stat '8821cu.ko': No such file or directory
> Makefile:1899: recipe for target 'install' failed
> make: *** [install] Error 1

I'm using ubuntu 16.04 LTS and the kernel version is 4.4.0.

**Comment by Yuan-W** [comment]
The file '8821cu.ko' has not been built yet. You may run `sudo make` to build it. Then `sudo make install` for installation.

**Comment by gavinweixin** [comment]
It works! Sorry to forget that...
Thank you very much.
BTW, is this driver only drives WiFi or both WiFi & Bluetooth?

**Comment by Yuan-W** [comment]
rtl8821cu is a WIFI chip. So this driver is WIFI only.

**Comment by gavinweixin** [comment]
Thanks.
But according to the [official website](http://www.realtek.com/products/productsView.aspx?Langid=1&PNid=21&PFid=60&Level=5&Conn=4&ProdID=386), it does have Bluetooth integrated.

**Comment by Yuan-W** [comment]
Sorry, just checked the spec and the driver details. It's could support both Bluetooth and WIFI. I haven't tested it with Bluetooth but it should work out of the box.

**Comment by gavinweixin** [comment]
Great.
