### ISSUE TITLE
can't add module on centos kernel 4.14.16

### ISSUE THREAD

**Issue by Jason-sss** [Yuan-W/rtl8821cu#2]
odprobe[9940]: ERROR: could not insert '8821cu': Unknown symbol in module, or unknown parameter (see dmesg)

**Comment by Yuan-W** [comment]
Could you post the output from dmesg here?

**Comment by zhangsd20** [comment]
hi,
   Does this driver have a requirement for the kernel version?

**Comment by Yuan-W** [comment]
Hi @zhangsd20 ,

I've just added kernel 4.19 and 4.20 support. This driver was tested with kernel 4.18 and 4.20. Theoretically, it shall work with any kernel version between 2.6 - 4.20.

**Comment by Yuan-W** [comment]
I'll close this issue since no reply from the responder for a long time.

**Comment by zhangsd20** [comment]
Ok,Thanks!
Whether this driver can be adapted on mips ?

**Comment by zhangsd20** [comment]
Load driver prompts the following error:
[   89.686836] 8821cu: Unknown symbol __floatsisf (err 0)
[   89.692515] 8821cu: Unknown symbol __gtdf2 (err 0)
[   89.697662] 8821cu: Unknown symbol __ltdf2 (err 0)
[   89.702839] 8821cu: Unknown symbol __lesf2 (err 0)
[   89.708102] 8821cu: Unknown symbol __gedf2 (err 0)
[   89.713582] 8821cu: Unknown symbol __floatunsidf (err 0)
[   89.719860] 8821cu: Unknown symbol __fixunsdfsi (err 0)
[   89.725402] 8821cu: Unknown symbol __fixsfsi (err 0)
[   89.730748] 8821cu: Unknown symbol __subsf3 (err 0)
[   89.735951] 8821cu: Unknown symbol __muldf3 (err 0)
[   89.741766] 8821cu: Unknown symbol __subdf3 (err 0)
[   89.746917] 8821cu: Unknown symbol __ledf2 (err 0)
[   89.752051] 8821cu: Unknown symbol __adddf3 (err 0)
[   89.757202] 8821cu: Unknown symbol __divdf3 (err 0)
[   89.762596] 8821cu: Unknown symbol __floatsidf (err 0)
[   89.768168] 8821cu: Unknown symbol __truncdfsf2 (err 0)
[   89.773735] 8821cu: Unknown symbol __fixdfsi (err 0)

**Comment by Yuan-W** [comment]
Cross compile is not tested. You could enable the cross compile flag and give it a try. There are some mips flags in the Makefile like CONFIG_PLATFORM_MIPS_AR9132. You may need to define your own flag for your mips toolchain.

Regarding the unknown symbol error, it seems that the C library cannot be found. Could you provide your build host and toolchain information?

**Comment by zhangsd20** [comment]
Hi,
Can you tell me your mailbox? so it is more convenient to communicate.
I will send you my Makefile.
Thanks!

**Comment by zhangsd20** [comment]
Hi,
  Attached is my makefile.
 Please help me find out where I am wrong.
Thank you very much!













在2019年03月12 10时20分，"Yuan"<notifications@github.com>写道：

Cross compile is not tested. You could enable the cross compile flag and give it a try. There are some mips flags in the Makefile like CONFIG_PLATFORM_MIPS_AR9132. You may need to define your own flag for your mips toolchain.
Regarding the unknown symbol error, it seems that the C library cannot be found. Could you provide your build host and toolchain information?

**Comment by zhangsd20** [comment]
Hi,

...
ifeq ($(CONFIG_MP_VHT_HW_TX_MODE), y)
EXTRA_CFLAGS += -DCONFIG_MP_VHT_HW_TX_MODE
ifeq ($(CONFIG_PLATFORM_I386_PC), y)
## For I386 X86 ToolChain use Hardware FLOATING
EXTRA_CFLAGS += -mhard-float
else
## For ARM ToolChain use Hardware FLOATING
EXTRA_CFLAGS += -mfloat-abi=hard
endif
endif
...

Should be the problem in this place, I use mips is not pc or arm this place need to be modified?

**Comment by Yuan-W** [comment]
You may check the Makefile for CONFIG_MP_VHT_HW_TX_MODE and CONFIG_PLATFORM_I386_PC. 

By default, CONFIG_MP_VHT_HW_TX_MODE = n and CONFIG_PLATFORM_I386_PC = y. If you want to build it for MIPS(OpenWRT and so on), you need to define your own flag like CONFIG_PLATFORM_MIPS_XXXXX which XXXXX is your chipset. 

After defining your flag, you may add a routine to set the cflag and corss_compile according to your own need for your CONFIG_PLATFORM_MIPS_XXXXX is y.

**Comment by zhangsd20** [comment]
PC:    EXTRA_CFLAGS += -mhard-float
ARM: EXTRA_CFLAGS += -mfloat-abi=hard

This module seems to be using floating point numbers, so this error will occur?
